package server

import (
	"encoding/json"
	"fmt"
	"testing"
	"time"

	"github.com/k0ngk0ng/wire-board/internal/game"
)

// Fixed legal networks, independently generated by the engine boundary tests.
// These are explicit middle-game fixtures, not claimed as natural full games.
func TestCatanTwoCaravansShortRoundHTTPRecovery(t *testing.T) {
	for _, tie := range []bool{false, true} {
		for _, mode := range []string{"manual", "autoplay", "timeout"} {
			t.Run(fmt.Sprintf("tie=%v/%s", tie, mode), func(t *testing.T) {
				s, ts, clients, id := newTwoScenarioFullTable(t, "caravans")
				state, err := game.NewCatanTwoCaravans(2, game.CatanOptions{})
				if err != nil {
					t.Fatal(err)
				}
				state.Turn, state.Catan.StartPlayer = 0, 0
				state.Catan.SetupStep, state.Phase = 4, "catan_turn"
				state.Catan.Two.Rolls = []int{2, 12}
				path := [][2]int{{55, 32}, {24, 21}, {26, 20}, {12, 11}, {53, 41}, {10, 6}, {9, 9}, {22, 19}, {54, 42}, {49, 38}, {64, 39}, {8, 8}, {5, 5}, {20, 14}, {0, 1}, {63, 49}, {7, 0}, {62, 48}, {67, 47}, {6, 7}}
				bids := []int{2, 1}
				if tie {
					path = [][2]int{{22, 19}, {24, 21}, {20, 14}, {0, 1}, {26, 20}, {55, 32}, {7, 0}, {53, 41}, {65, 42}, {12, 11}, {67, 47}, {6, 6}, {23, 7}, {66, 51}, {21, 18}, {70, 50}, {69, 53}, {71, 52}, {60, 46}, {56, 43}}
					bids[1] = 2
				}
				wagons := []map[string]int{}
				for _, w := range path {
					wagons = append(wagons, map[string]int{"edge": w[0], "from": w[1]})
				}
				raw, _ := json.Marshal(wagons)
				if err = json.Unmarshal(raw, &state.Catan.Caravans.Wagons); err != nil {
					t.Fatal(err)
				}
				for p, bid := range bids {
					state.Catan.Players[p].Resources[2] = bid
					state.Catan.Bank[2] -= bid
				}
				s.rooms[id].Game = state
				// Unique-winner fixture permits a later tie round using the final
				// physical wagon. The tie fixture instead closes the whole network.
				rounds := 2
				if tie {
					rounds = 1
				}
				for round := 0; round < rounds; round++ {
					r := s.rooms[id]
					r.Game.Phase = "catan_turn"
					r.Game.Catan.Two.Rolls = []int{2, 12}
					r.Game.Catan.Caravans.Built = true
					r.TurnDeadline = time.Now().Add(45 * time.Second).UnixMilli()
					if err = s.save(r); err != nil {
						t.Fatal(err)
					}
					active := r.Game.Turn
					clients[active].command(current(clients[active]), "action", game.Action{Type: "catan_end"}, 200)
					for range 2 {
						actor := s.rooms[id].Game.CatanPendingActor()
						bid := 0
						if round == 0 {
							bid = bids[actor]
						}
						clients[actor].command(current(clients[actor]), "action", game.Action{Type: "catan_caravan_bid", Tokens: []int{0, 0, bid, 0, 0}}, 200)
					}
					s, ts = restartRiversHTTP(t, s, ts, clients, id)
					r = s.rooms[id]
					actor := r.Game.CatanPendingActor()
					for p, client := range clients {
						view := current(client)["game"].(map[string]any)["catan"].(map[string]any)
						c := view["caravans"].(map[string]any)
						if c["placementLimit"] != float64(1) || c["canAct"] != (p == actor) {
							t.Fatal("short round public choices or owner")
						}
						for owner, seat := range view["players"].([]any) {
							if owner != p && seat.(map[string]any)["resources"] != nil {
								t.Fatal("private hand exposed")
							}
						}
					}
					a, err := r.Game.BotAction(actor)
					if err != nil {
						t.Fatal(err)
					}
					for _, p := range []int{1 - actor, 2} {
						clients[p].command(current(clients[p]), "action", a, 400)
					}
					request := map[string]any{"type": "action", "version": r.Version, "nonce": fmt.Sprintf("short-round-%d", round), "action": a}
					switch mode {
					case "manual":
						clients[actor].post("/api/rooms/"+id, request, 200)
					case "autoplay":
						setAutoPlay(clients[actor], current(clients[actor]), true, 200)
						s.mu.Lock()
						s.rooms[id].BotAt = 0
						s.runBots(time.Now())
						s.mu.Unlock()
						setAutoPlay(clients[actor], current(clients[actor]), false, 200)
					case "timeout":
						s.mu.Lock()
						s.rooms[id].TurnDeadline = time.Now().Add(-time.Second).UnixMilli()
						s.expireSetups(time.Now())
						s.mu.Unlock()
						reclaimTimeoutHumans(t, s, clients, id)
					}
					r = s.rooms[id]
					if r.Game.Phase != "catan_roll" || r.Game.Turn != 1-active || r.Game.Catan.Caravans.Pending != nil || len(r.Game.Catan.Caravans.Wagons) != 21+round || len(r.Game.Catan.Caravans.ShortRounds) != round+1 || r.Game.Catan.Bank[2] != 19 {
						t.Fatal("short round stuck or duplicated refund")
					}
					if left := r.TurnDeadline - time.Now().UnixMilli(); left < 119000 || left > 120000 {
						t.Fatal("next turn missing fresh clock", left)
					}
					before, _ := json.Marshal(r)
					s, ts = restartRiversHTTP(t, s, ts, clients, id)
					if mode == "manual" {
						clients[actor].post("/api/rooms/"+id, request, 200)
					}
					after, _ := json.Marshal(s.rooms[id])
					if string(before) != string(after) {
						t.Fatal("restart/replay changed completed short round")
					}
					assertTwoHTTPInventory(t, s.rooms[id].Game)
				}
			})
		}
	}
}
