package server

import (
	"encoding/json"
	"fmt"
	"os"
	"slices"
	"testing"
	"time"

	"github.com/k0ngk0ng/wire-board/internal/game"
)

// Fixtures were generated by the private official-board constructor and real
// BotAction/Apply initial settlement/city/road placements. The public room
// recipe remains disabled; these are response tests, not full-game acceptance.
func attackHTTPFixture(t *testing.T, n int) *game.State {
	t.Helper()
	data, e := os.ReadFile(fmt.Sprintf("testdata/catan_attack_%d.json", n))
	if e != nil {
		t.Fatal(e)
	}
	var state game.State
	if e = json.Unmarshal(data, &state); e != nil {
		t.Fatal(e)
	}
	if n == 6 {
		state.Turn = 3
		state.Catan.Paired.Second = true
	}
	if state.Catan.Attack == nil || state.Catan.Attack.Rules != "catan-barbarian-attack-2025" || state.Phase != "catan_turn" || state.Catan.SetupStep != state.Catan.SetupLimit() {
		t.Fatal("invalid attack response fixture")
	}
	return &state
}

func prepareAttackHTTPCard(t *testing.T, state *game.State, card string) {
	t.Helper()
	g, p := state.Catan, state.Turn
	a := g.Attack
	i := slices.Index(a.Deck, card)
	if i < 0 {
		t.Fatal("fixture card missing")
	}
	a.Deck[i], a.Deck[len(a.Deck)-1] = a.Deck[len(a.Deck)-1], a.Deck[i]
	for c, want := range []int{0, 0, 1, 1, 1} {
		g.Bank[c] += g.Players[p].Resources[c] - want
		g.Players[p].Resources[c] = want
	}
}

func TestCatanAttackCardsHTTPResponsesClockAutoplayTimeoutAndRestart(t *testing.T) {
	for _, n := range []int{3, 6} {
		for _, card := range []string{"capture", "knighthood", "swift_knight", "treason"} {
			for _, mode := range []string{"manual", "autoplay", "timeout"} {
				t.Run(fmt.Sprintf("%d/%s/%s", n, card, mode), func(t *testing.T) {
					s, ts, clients, id, _, _ := newFishingActionTable(t, n, "catan_turn", "resource")
					state := attackHTTPFixture(t, n)
					actor := state.Turn
					prepareAttackHTTPCard(t, state, card)
					s.mu.Lock()
					r := s.rooms[id]
					r.Game = state
					r.TurnDeadline = time.Now().Add(45 * time.Second).UnixMilli()
					if e := s.save(r); e != nil {
						t.Fatal(e)
					}
					s.mu.Unlock()
					for round := 1; round <= 2; round++ {
						if round == 2 {
							s.mu.Lock()
							prepareAttackHTTPCard(t, s.rooms[id].Game, card)
							if e := s.save(s.rooms[id]); e != nil {
								t.Fatal(e)
							}
							s.mu.Unlock()
						}
						clients[actor].command(current(clients[actor]), "action", game.Action{Type: "catan_buy_dev"}, 200)
						r = s.rooms[id]
						a := r.Game.Catan.Attack
						if r.Game.Phase != "catan_attack_card" || r.Game.CatanPendingActor() != actor || a.Pending.ID != round || a.Pending.Card != card || r.Game.Turn != actor {
							t.Fatal("wrong mandatory response")
						}
						if left := r.TurnDeadline - time.Now().UnixMilli(); left < 119000 || left > 120000 {
							t.Fatal("missing full response clock", left)
						}
						remaining := r.CatanTimeLeft
						if remaining < 40000 || remaining > 45000 {
							t.Fatal("lost action clock", remaining)
						}
						choice, e := r.Game.BotAction(actor)
						if e != nil {
							t.Fatal(e)
						}
						before, _ := json.Marshal(r)
						for _, p := range []int{(actor + 1) % n, n} {
							clients[p].command(current(clients[p]), "action", choice, 400)
						}
						clients[actor].command(current(clients[actor]), "action", game.Action{Type: "catan_end"}, 400)
						bad := choice
						bad.Prompt = round - 1
						clients[actor].command(current(clients[actor]), "action", bad, 400)
						after, _ := json.Marshal(s.rooms[id])
						if string(before) != string(after) {
							t.Fatal("invalid choice changed room or timer")
						}
						s, ts = restartRiversHTTP(t, s, ts, clients, id)
						for viewer, c := range clients {
							v := current(c)["game"].(map[string]any)["catan"].(map[string]any)
							pub := v["attack"].(map[string]any)
							if pub["deck"] != nil || pub["canAct"] != (viewer == actor) || pub["pending"].(map[string]any)["card"] != card {
								t.Fatal("card view privacy")
							}
							if viewer != actor && (pub["targets"] != nil || pub["edges"] != nil || pub["sources"] != nil || pub["destinations"] != nil) {
								t.Fatal("observer/other seat controls")
							}
							for owner, raw := range v["players"].([]any) {
								if owner != viewer && raw.(map[string]any)["resources"] != nil {
									t.Fatal("private hand leaked")
								}
							}
						}
						at := time.Now()
						switch mode {
						case "manual":
							clients[actor].command(current(clients[actor]), "action", choice, 200)
						case "autoplay":
							setAutoPlay(clients[actor], current(clients[actor]), true, 200)
							s.mu.Lock()
							s.rooms[id].BotAt = 0
							s.runBots(at)
							s.mu.Unlock()
							setAutoPlay(clients[actor], current(clients[actor]), false, 200)
						case "timeout":
							at = time.UnixMilli(s.rooms[id].TurnDeadline)
							s.mu.Lock()
							s.expireSetups(at)
							s.mu.Unlock()
						}
						r = s.rooms[id]
						if r.Game.Phase != "catan_turn" || r.Game.CatanPendingActor() != -1 || r.Game.Turn != actor || r.Game.Catan.Attack.Pending != nil || len(r.Game.Catan.Attack.Discard) != round || r.Game.Catan.TurnSerial != 1 {
							t.Fatal("card did not finish exactly once in original action")
						}
						if n == 6 && !r.Game.Catan.Paired.Second {
							t.Fatal("secondary action lost")
						}
						if left := r.TurnDeadline - at.UnixMilli(); left < remaining || left > remaining+1000 {
							t.Fatal("original action time was not restored", left, remaining)
						}
						if mode == "timeout" {
							if !r.Seats[actor].AutoPlay || !r.Seats[actor].TimeoutAutoPlay {
								t.Fatal("timeout did not persist computer control")
							}
							setAutoPlay(clients[actor], current(clients[actor]), false, 200)
							r = s.rooms[id]
							// Return the synthetic future clock to wall time before the next
							// purchase; do not grant 120 extra seconds to its action phase.
							s.mu.Lock()
							r.TurnDeadline = time.Now().Add(45 * time.Second).UnixMilli()
							s.save(r)
							s.mu.Unlock()
						}
						s, ts = restartRiversHTTP(t, s, ts, clients, id)
						clients[actor].command(current(clients[actor]), "action", choice, 400)
					}
				})
			}
		}
	}
}
