package game

// National-war base roster, pinned QSanguosha-For-Hegemony 2.0.0
// c787f870ac8f30084800c08782c89ba4ca32b039. These IDs never enter identity games.
// Skills with different rules have separate IDs even when their names match.
var sgHegemonyGenerals = []SGGeneral{
	{"heg_caocao", "曹操", "wei", 4, false, []string{"jianxiong"}},
	{"heg_simayi", "司马懿", "wei", 3, false, []string{"fankui", "guicai"}},
	{"heg_xiahoudun", "夏侯惇", "wei", 4, false, []string{"ganglie"}},
	{"heg_zhangliao", "张辽", "wei", 4, false, []string{"tuxi"}},
	{"heg_xuchu", "许褚", "wei", 4, false, []string{"luoyi"}},
	{"heg_guojia", "郭嘉", "wei", 3, false, []string{"tiandu", "yiji"}},
	{"heg_zhenji", "甄姬", "wei", 3, true, []string{"qingguo", "luoshen"}},
	{"heg_xiahouyuan", "夏侯渊", "wei", 4, false, []string{"shensu"}},
	{"heg_zhanghe", "张郃", "wei", 4, false, []string{"qiaobian"}},
	{"heg_xuhuang", "徐晃", "wei", 4, false, []string{"duanliang"}},
	{"heg_caoren", "曹仁", "wei", 4, false, []string{"jushou"}},
	{"heg_dianwei", "典韦", "wei", 4, false, []string{"qiangxi"}},
	{"heg_xunyu", "荀彧", "wei", 3, false, []string{"quhu", "jieming"}},
	{"heg_caopi", "曹丕", "wei", 3, false, []string{"xingshang", "fangzhu"}},
	{"heg_yuejin", "乐进", "wei", 4, false, []string{"heg_xiaoguo"}},
	{"heg_liubei", "刘备", "shu", 4, false, []string{"heg_rende"}},
	{"heg_guanyu", "关羽", "shu", 5, false, []string{"wusheng"}},
	{"heg_zhangfei", "张飞", "shu", 4, false, []string{"paoxiao"}},
	{"heg_zhugeliang", "诸葛亮", "shu", 3, false, []string{"guanxing", "kongcheng"}},
	{"heg_zhaoyun", "赵云", "shu", 4, false, []string{"longdan"}},
	{"heg_machao", "马超", "shu", 4, false, []string{"mashu", "tieji"}},
	{"heg_huangyueying", "黄月英", "shu", 3, true, []string{"heg_jizhi", "qicai"}},
	{"heg_huangzhong", "黄忠", "shu", 4, false, []string{"liegong"}},
	{"heg_weiyan", "魏延", "shu", 4, false, []string{"kuanggu"}},
	{"heg_pangtong", "庞统", "shu", 3, false, []string{"lianhuan", "niepan"}},
	{"heg_wolong", "卧龙诸葛亮", "shu", 3, false, []string{"huoji", "kanpo", "bazhen"}},
	{"heg_liushan", "刘禅", "shu", 3, false, []string{"xiangle", "fangquan"}},
	{"heg_menghuo", "孟获", "shu", 4, false, []string{"huoshou", "zaiqi"}},
	{"heg_zhurong", "祝融", "shu", 4, true, []string{"juxiang", "lieren"}},
	{"heg_ganfuren", "甘夫人", "shu", 3, true, []string{"heg_shushen", "heg_shenzhi"}},
	{"heg_sunquan", "孙权", "wu", 4, false, []string{"heg_zhiheng"}},
	{"heg_ganning", "甘宁", "wu", 4, false, []string{"qixi"}},
	{"heg_lvmeng", "吕蒙", "wu", 4, false, []string{"keji"}},
	{"heg_huanggai", "黄盖", "wu", 4, false, []string{"kurou"}},
	{"heg_zhouyu", "周瑜", "wu", 3, false, []string{"yingzi", "fanjian"}},
	{"heg_daqiao", "大乔", "wu", 3, true, []string{"guose", "liuli"}},
	{"heg_luxun", "陆逊", "wu", 3, false, []string{"qianxun", "heg_duoshi"}},
	{"heg_sunshangxiang", "孙尚香", "wu", 3, true, []string{"jieyin", "xiaoji"}},
	{"heg_sunjian", "孙坚", "wu", 4, false, []string{"yinghun"}},
	{"heg_xiaoqiao", "小乔", "wu", 3, true, []string{"tianxiang", "hongyan"}},
	{"heg_taishici", "太史慈", "wu", 4, false, []string{"tianyi"}},
	{"heg_zhoutai", "周泰", "wu", 4, false, []string{"buqu"}},
	{"heg_lusu", "鲁肃", "wu", 3, false, []string{"haoshi", "dimeng"}},
	{"heg_erzhang", "张昭＆张纮", "wu", 3, false, []string{"zhijian", "guzheng"}},
	{"heg_dingfeng", "丁奉", "wu", 4, false, []string{"heg_duanbing", "heg_fenxun"}},
	{"heg_huatuo", "华佗", "qun", 3, false, []string{"jijiu", "qingnang"}},
	{"heg_lvbu", "吕布", "qun", 5, false, []string{"wushuang"}},
	{"heg_diaochan", "貂蝉", "qun", 3, true, []string{"heg_lijian", "biyue"}},
	{"heg_yuanshao", "袁绍", "qun", 4, false, []string{"luanji"}},
	{"heg_yanliangwenchou", "颜良＆文丑", "qun", 4, false, []string{"shuangxiong"}},
	{"heg_jiaxu", "贾诩", "qun", 3, false, []string{"wansha", "luanwu", "weimu"}},
	{"heg_pangde", "庞德", "qun", 4, false, []string{"mashu", "mengjin"}},
	{"heg_zhangjiao", "张角", "qun", 3, false, []string{"leiji", "guidao"}},
	{"heg_caiwenji", "蔡文姬", "qun", 3, true, []string{"beige", "heg_duanchang"}},
	{"heg_mateng", "马腾", "qun", 4, false, []string{"mashu", "heg_xiongyi"}},
	{"heg_kongrong", "孔融", "qun", 3, false, []string{"heg_mingshi", "heg_lirang"}},
	{"heg_jiling", "纪灵", "qun", 4, false, []string{"heg_shuangren"}},
	{"heg_tianfeng", "田丰", "qun", 3, false, []string{"heg_sijian", "heg_suishi"}},
	{"heg_panfeng", "潘凤", "qun", 4, false, []string{"heg_kuangfu"}},
	{"heg_zoushi", "邹氏", "qun", 3, true, []string{"heg_huoshui", "heg_qingcheng"}},
}

var sgHegemonyCompanions = [][2]string{
	{"heg_caocao", "heg_dianwei"},
	{"heg_caocao", "heg_xuchu"},
	{"heg_xiahoudun", "heg_xiahouyuan"},
	{"heg_caopi", "heg_zhenji"},
	{"heg_liubei", "heg_guanyu"},
	{"heg_liubei", "heg_zhangfei"},
	{"heg_liubei", "heg_ganfuren"},
	{"heg_zhugeliang", "heg_huangyueying"},
	{"heg_zhaoyun", "heg_liushan"},
	{"heg_huangzhong", "heg_weiyan"},
	{"heg_wolong", "heg_huangyueying"},
	{"heg_wolong", "heg_pangtong"},
	{"heg_menghuo", "heg_zhurong"},
	{"heg_sunquan", "heg_zhoutai"},
	{"heg_zhouyu", "heg_huanggai"},
	{"heg_zhouyu", "heg_xiaoqiao"},
	{"heg_daqiao", "heg_xiaoqiao"},
	{"heg_lvbu", "heg_diaochan"},
	{"heg_yuanshao", "heg_yanliangwenchou"},
}

// IDs are disjoint from the 108 classic + 52 military cards. Old IDs and
// already-saved physical cards retain their meaning across every mode.
var sgHegemonyCards = []SGCard{
	{ID: 1001, Kind: "slash", Suit: 0, Rank: 5},
	{ID: 1002, Kind: "slash", Suit: 0, Rank: 7},
	{ID: 1003, Kind: "slash", Suit: 0, Rank: 8},
	{ID: 1004, Kind: "slash", Suit: 0, Rank: 8},
	{ID: 1005, Kind: "slash", Suit: 0, Rank: 9},
	{ID: 1006, Kind: "slash", Suit: 0, Rank: 10},
	{ID: 1007, Kind: "slash", Suit: 0, Rank: 11},
	{ID: 1008, Kind: "slash", Suit: 2, Rank: 2},
	{ID: 1009, Kind: "slash", Suit: 2, Rank: 3},
	{ID: 1010, Kind: "slash", Suit: 2, Rank: 4},
	{ID: 1011, Kind: "slash", Suit: 2, Rank: 5},
	{ID: 1012, Kind: "slash", Suit: 2, Rank: 8},
	{ID: 1013, Kind: "slash", Suit: 2, Rank: 9},
	{ID: 1014, Kind: "slash", Suit: 2, Rank: 10},
	{ID: 1015, Kind: "slash", Suit: 2, Rank: 11},
	{ID: 1016, Kind: "slash", Suit: 2, Rank: 11},
	{ID: 1017, Kind: "slash", Suit: 1, Rank: 10},
	{ID: 1018, Kind: "slash", Suit: 1, Rank: 12},
	{ID: 1019, Kind: "slash", Suit: 3, Rank: 10},
	{ID: 1020, Kind: "slash", Suit: 3, Rank: 11},
	{ID: 1021, Kind: "slash", Suit: 3, Rank: 12},
	{ID: 1022, Kind: "fire_slash", Suit: 1, Rank: 4},
	{ID: 1023, Kind: "fire_slash", Suit: 3, Rank: 4},
	{ID: 1024, Kind: "fire_slash", Suit: 3, Rank: 5},
	{ID: 1025, Kind: "thunder_slash", Suit: 0, Rank: 6},
	{ID: 1026, Kind: "thunder_slash", Suit: 0, Rank: 7},
	{ID: 1027, Kind: "thunder_slash", Suit: 2, Rank: 6},
	{ID: 1028, Kind: "thunder_slash", Suit: 2, Rank: 7},
	{ID: 1029, Kind: "thunder_slash", Suit: 2, Rank: 8},
	{ID: 1030, Kind: "jink", Suit: 1, Rank: 2},
	{ID: 1031, Kind: "jink", Suit: 1, Rank: 11},
	{ID: 1032, Kind: "jink", Suit: 1, Rank: 13},
	{ID: 1033, Kind: "jink", Suit: 3, Rank: 2},
	{ID: 1034, Kind: "jink", Suit: 3, Rank: 3},
	{ID: 1035, Kind: "jink", Suit: 3, Rank: 6},
	{ID: 1036, Kind: "jink", Suit: 3, Rank: 7},
	{ID: 1037, Kind: "jink", Suit: 3, Rank: 7},
	{ID: 1038, Kind: "jink", Suit: 3, Rank: 8},
	{ID: 1039, Kind: "jink", Suit: 3, Rank: 8},
	{ID: 1040, Kind: "jink", Suit: 3, Rank: 9},
	{ID: 1041, Kind: "jink", Suit: 3, Rank: 10},
	{ID: 1042, Kind: "jink", Suit: 3, Rank: 11},
	{ID: 1043, Kind: "jink", Suit: 3, Rank: 13},
	{ID: 1044, Kind: "peach", Suit: 1, Rank: 4},
	{ID: 1045, Kind: "peach", Suit: 1, Rank: 6},
	{ID: 1046, Kind: "peach", Suit: 1, Rank: 7},
	{ID: 1047, Kind: "peach", Suit: 1, Rank: 8},
	{ID: 1048, Kind: "peach", Suit: 1, Rank: 9},
	{ID: 1049, Kind: "peach", Suit: 1, Rank: 10},
	{ID: 1050, Kind: "peach", Suit: 1, Rank: 12},
	{ID: 1051, Kind: "peach", Suit: 3, Rank: 2},
	{ID: 1052, Kind: "analeptic", Suit: 0, Rank: 9},
	{ID: 1053, Kind: "analeptic", Suit: 2, Rank: 9},
	{ID: 1054, Kind: "analeptic", Suit: 3, Rank: 9},
	{ID: 1055, Kind: "crossbow", Suit: 3, Rank: 1},
	{ID: 1056, Kind: "double_sword", Suit: 0, Rank: 2},
	{ID: 1057, Kind: "qinggang_sword", Suit: 0, Rank: 6},
	{ID: 1058, Kind: "ice_sword", Suit: 0, Rank: 2},
	{ID: 1059, Kind: "spear", Suit: 0, Rank: 12},
	{ID: 1060, Kind: "fan", Suit: 3, Rank: 1},
	{ID: 1061, Kind: "axe", Suit: 3, Rank: 5},
	{ID: 1062, Kind: "kylin_bow", Suit: 1, Rank: 5},
	{ID: 1063, Kind: "six_swords", Suit: 3, Rank: 6},
	{ID: 1064, Kind: "triblade", Suit: 3, Rank: 12},
	{ID: 1065, Kind: "eight_diagram", Suit: 0, Rank: 2},
	{ID: 1066, Kind: "renwang_shield", Suit: 2, Rank: 2},
	{ID: 1067, Kind: "vine", Suit: 2, Rank: 2},
	{ID: 1068, Kind: "silver_lion", Suit: 2, Rank: 1},
	{ID: 1069, Kind: "jueying", Suit: 0, Rank: 5},
	{ID: 1070, Kind: "dilu", Suit: 2, Rank: 5},
	{ID: 1071, Kind: "zhuahuangfeidian", Suit: 1, Rank: 13},
	{ID: 1072, Kind: "chitu", Suit: 1, Rank: 5},
	{ID: 1073, Kind: "dayuan", Suit: 0, Rank: 13},
	{ID: 1074, Kind: "zixing", Suit: 3, Rank: 13},
	{ID: 1075, Kind: "amazing_grace", Suit: 1, Rank: 3},
	{ID: 1076, Kind: "god_salvation", Suit: 1, Rank: 1},
	{ID: 1077, Kind: "savage_assault", Suit: 0, Rank: 13},
	{ID: 1078, Kind: "savage_assault", Suit: 2, Rank: 7},
	{ID: 1079, Kind: "archery_attack", Suit: 1, Rank: 1},
	{ID: 1080, Kind: "duel", Suit: 0, Rank: 1},
	{ID: 1081, Kind: "duel", Suit: 2, Rank: 1},
	{ID: 1082, Kind: "ex_nihilo", Suit: 1, Rank: 7},
	{ID: 1083, Kind: "ex_nihilo", Suit: 1, Rank: 8},
	{ID: 1084, Kind: "snatch", Suit: 0, Rank: 3},
	{ID: 1085, Kind: "snatch", Suit: 0, Rank: 4},
	{ID: 1086, Kind: "snatch", Suit: 3, Rank: 3},
	{ID: 1087, Kind: "dismantlement", Suit: 0, Rank: 3},
	{ID: 1088, Kind: "dismantlement", Suit: 0, Rank: 4},
	{ID: 1089, Kind: "dismantlement", Suit: 1, Rank: 12},
	{ID: 1090, Kind: "iron_chain", Suit: 0, Rank: 12},
	{ID: 1091, Kind: "iron_chain", Suit: 2, Rank: 12},
	{ID: 1092, Kind: "iron_chain", Suit: 2, Rank: 13},
	{ID: 1093, Kind: "fire_attack", Suit: 1, Rank: 2},
	{ID: 1094, Kind: "fire_attack", Suit: 1, Rank: 3},
	{ID: 1095, Kind: "collateral", Suit: 2, Rank: 12},
	{ID: 1096, Kind: "nullification", Suit: 0, Rank: 11},
	{ID: 1097, Kind: "heg_nullification", Suit: 2, Rank: 13},
	{ID: 1098, Kind: "heg_nullification", Suit: 3, Rank: 12},
	{ID: 1099, Kind: "await_exhausted", Suit: 1, Rank: 11},
	{ID: 1100, Kind: "await_exhausted", Suit: 3, Rank: 4},
	{ID: 1101, Kind: "known_both", Suit: 2, Rank: 3},
	{ID: 1102, Kind: "known_both", Suit: 2, Rank: 4},
	{ID: 1103, Kind: "befriend_attacking", Suit: 1, Rank: 9},
	{ID: 1104, Kind: "indulgence", Suit: 2, Rank: 6},
	{ID: 1105, Kind: "indulgence", Suit: 1, Rank: 6},
	{ID: 1106, Kind: "supply_shortage", Suit: 0, Rank: 10},
	{ID: 1107, Kind: "supply_shortage", Suit: 2, Rank: 10},
	{ID: 1108, Kind: "lightning", Suit: 0, Rank: 1},
}
