// Stable English city keys are shared by the map and destination tickets.
export const cityChinese: Record<string, string> = {
  Atlanta: "亚特兰大",
  Boston: "波士顿",
  Calgary: "卡尔加里",
  Charleston: "查尔斯顿",
  Chicago: "芝加哥",
  Dallas: "达拉斯",
  Denver: "丹佛",
  Duluth: "德卢斯",
  "El Paso": "埃尔帕索",
  Helena: "海伦娜",
  Houston: "休斯敦",
  "Kansas City": "堪萨斯城",
  "Las Vegas": "拉斯维加斯",
  "Little Rock": "小石城",
  "Los Angeles": "洛杉矶",
  Miami: "迈阿密",
  Montreal: "蒙特利尔",
  Nashville: "纳什维尔",
  "New Orleans": "新奥尔良",
  "New York": "纽约",
  "Oklahoma City": "俄克拉何马城",
  Omaha: "奥马哈",
  Phoenix: "凤凰城",
  Pittsburgh: "匹兹堡",
  Portland: "波特兰",
  Raleigh: "罗利",
  "Saint Louis": "圣路易斯",
  "Salt Lake City": "盐湖城",
  "San Francisco": "旧金山",
  "Santa Fe": "圣菲",
  "Sault St. Marie": "苏圣玛丽",
  Seattle: "西雅图",
  Toronto: "多伦多",
  Vancouver: "温哥华",
  Washington: "华盛顿",
  Winnipeg: "温尼伯",
};
export const cityName = (name: string, locale = "zh-CN") =>
  locale === "zh-CN" ? cityChinese[name] || name : name;
